/* Shared navigation, footer and small progressive-enhancement interactions. */
const header = document.querySelector('.site-header');
const footer = document.querySelector('.site-footer');
const current = location.pathname.split('/').pop() || 'index.html';
const nav = (file, label) => `<a class="${current === file ? 'active' : ''}" href="${file}">${label}</a>`;
header.innerHTML = `<div class="topbar"><div class="container"><span>NIGERIA OFFICE</span><span>27A Alternative route, Chevron Lekki, Lagos Nigeria</span><a href="mailto:info@iemacert.com">info@iemacert.com</a><a href="tel:+2348134831027">+234 813 483 1027</a></div></div><div class="navbar container"><a class="logo" href="index.html"><span>IEMA</span><small>CERT</small></a><button class="menu-toggle" aria-label="Toggle navigation" aria-expanded="false">☰</button><nav>${nav('index.html','Home')}${nav('aboutus.html','About Us')}${nav('ourservices.html','Our Services')}${nav('contactus.html','Contact Us')}<a class="nav-quote" href="https://iiema.org/">Get A Quote</a></nav></div>`;
footer.innerHTML = `<div class="container footer-grid"><div><a class="logo footer-logo" href="index.html"><span>IEMA</span><small>CERT</small></a><p>IEMA Standards Limited provides credible conformity assessment, inspection, testing and certification services worldwide.</p><div class="socials"><a href="#">f</a><a href="#">◎</a><a href="#">𝕏</a><a href="#">in</a></div></div><div><h4>Quick links</h4><a href="aboutus.html">About Us</a><a href="ourservices.html">Our Services</a><a href="contactus.html">Contact Us</a><a href="https://certificates.iiema.org/">Verify ISO Certificate</a></div><div><h4>Get in Touch</h4><p>27A Alternative drive, near Waterbrook school, Chevron Lekki, Lagos Nigeria</p><p>+234 813 483 1027<br>+234 703 469 0322</p><p>info@iemacert.com</p></div><div><h4>Social Network</h4><p>Follow IEMA for company updates, standards and insights.</p><div class="socials"><a href="#">f</a><a href="#">◎</a><a href="#">𝕏</a><a href="#">in</a></div></div></div><div class="copyright">© 2025 IEMA STANDARDS LTD. All rights reserved.</div>`;
document.querySelector('.menu-toggle').addEventListener('click', (e) => { const open = header.classList.toggle('menu-open'); e.currentTarget.setAttribute('aria-expanded', open); });
document.querySelector('#contactForm')?.addEventListener('submit', (e) => { e.preventDefault(); e.currentTarget.querySelector('.form-note').textContent = 'Thank you. Your message is ready to be sent to IEMA.'; e.currentTarget.reset(); });
